name = input("What is your name? ")
print("Hello, " + name + ". Welcome to the adventure game!")
print("You are on a deserted island. You can go north, south, east, or west.")
direction = input("Which direction would you like to go? ")
print("You are going " + direction + ".")
print("You have encountered a wild animal!")
print("You can fight, run, or hide.")
action = input("What would you like to do? ")
print("You have chosen to " + action + ".")
print("You have survived the encounter!")
print("You have won the game!")
print("Congratulations, " + name + "!")

# Path: adventure2.py
name = input("What is your name? ")
print("Hello, " + name + ". Welcome to the adventure game!")
print("You are on a deserted island. You can go north, south, east, or west.")
direction = input("Which direction would you like to go? ")
print("You are going " + direction + ".")
print("You have encountered a wild animal!")
print("You can fight, run, or hide.")
action = input("What would you like to do? ")
print("You have chosen to " + action + ".")
print("You have been defeated!")
print("You have lost the game!")

# Path: adventure3.py
name = input("What is your name? ")
print("Hello, " + name + ". Welcome to the adventure game!")
print("You are on a deserted island. You can go north, south, east, or west.")
direction = input("Which direction would you like to go? ")
print("You are going " + direction + ".")
print("You have encountered a wild animal!")
print("You can fight, run, or hide.")
action = input("What would you like to do? ")
print("You have chosen to " + action + ".")
print("You have been captured!")
print("You have lost the game!")

# Path: adventure4.py
name = input("What is your name? ")
print("Hello, " + name + ". Welcome to the adventure game!")
print("You are on a deserted island. You can go north, south, east, or west.")
direction = input("Which direction would you like to go? ")
print("You are going " + direction + ".")
print("You have encountered a wild animal!")
print("You can fight, run, or hide.")
action = input("What would you like to do? ")
print("You have chosen to " + action + ".")
print("You have been captured!")
print("You have lost the game!")

# Path: adventure5.py
name = input("What is your name? ")
print("Hello, " + name + ". Welcome to the adventure game!")
print("You are on a deserted island. You can go north, south, east, or west.")
direction = input("Which direction would you like to go? ")
print("You are going " + direction + ".")
print("You have encountered a wild animal!")
print("You can fight, run, or hide.")
action = input("What would you like to do? ")
print("You have chosen to " + action + ".")
print("You have been captured!")
print("You have lost the game!")

# Path: adventure6.py
name = input("What is your name? ")
print("Hello, " + name + ". Welcome to the adventure game!")
print("You are on a deserted island. You can go north, south, east, or west.")
direction = input("Which direction would you like to go? ")
print("You are going " + direction + ".")
print("You have encountered a wild animal!")
print("You can fight, run, or hide.")
action = input("What would you like to do? ")
print("You have chosen to " + action + ".")
print("You have been captured!")
print("You have lost the game!")

# Path: adventure7.py
name = input("What is your name? ")
print("Hello, " + name + ". Welcome to the adventure game!")
print("You are on a deserted island. You can go north, south, east, or west.")
direction = input("Which direction would you like to go? ")
print("You are going " + direction + ".")
print("You have encountered a wild animal!")
print("You can fight, run, or hide.")
action = input("What would you like to do? ")
print("You have chosen to " + action + ".")
print("You have been captured!")
print("You have lost the game!")

# Path: adventure8.py
name = input("What is your name? ")
print("Hello, " + name + ". Welcome to the adventure game!")
print("You are on a deserted island. You can go north, south, east, or west.")
direction = input("Which direction would you like to go? ")
print("You are going " + direction + ".")
print("You have encountered a wild animal!")
print("You can fight, run, or hide.")
action = input("What would you like to do? ")
print("You have chosen to " + action + ".")
print("You have been captured!")
print("You have lost the game!")

# Path: adventure9.py
name = input("What is your name? ")
print("Hello, " + name + ". Welcome to the adventure game!")
print("You are on a deserted island. You can go north, south, east, or west.")
direction = input("Which direction would you like to go? ")
print("You are going " + direction + ".")
print("You have encountered a wild animal!")
print("You can fight, run, or hide.")
action = input("What would you like to do? ")
print("You have chosen to " + action + ".")
print("You have been captured!")
print("You have lost the game!")

# Path: adventure10.py
name = input("What is your name? ")
print("Hello, " + name + ". Welcome to the adventure game!")
print("You are on a deserted island. You can go north, south, east, or west.")
direction = input("Which direction would you like to go? ")
print("You are going " + direction + ".")
print("You have encountered a wild animal!")
print("You can fight, run, or hide.")
action = input("What would you like to do? ")
print("You have chosen to " + action + ".")
print("You have been captured!")
print("You have lost the game!")
